<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
		<RootNamespace>PeterJuhasz.Text.Separated.Tests</RootNamespace>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="*" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="*" />
		<PackageReference Include="MSTest.TestAdapter" Version="*" />
		<PackageReference Include="MSTest.TestFramework" Version="*" />
		<PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\PeterJuhasz.Text.Separated\PeterJuhasz.Text.Separated.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
	</ItemGroup>

</Project>
